name: fikra_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # دعم الكتابة بالعربية وRTL
  flutter_localizations:
    sdk: flutter

  # لاختيار الصور من المعرض
  image_picker: ^0.8.7+5

  # إدارة الحالة
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png   # ✅ شعار التطبيق
    - assets/images/           # لو حابب تضيف صور تانية لاحقاً
